yarnPath: .yarn/releases/yarn-4.12.0.cjs

compressionLevel: mixed

logFilters:
  - code: YN0013
    level: discard
  - code: YN0019
    level: discard

packageExtensions:
  "@commitlint/load@*":
    dependencies:
      "@types/node": "^22.18.6"
      "typescript": "^5.9.3"
