name: Run tests
description: Prepare workspace and run project tests.

inputs:
  node-version:
    description: Node.js version used for cache key.
    required: true
  test-command:
    description: Shell command used to run tests.
    required: false
    default: yarn test:coverage

runs:
  using: composite
  steps:
    - name: Setup workspace
      uses: ./.github/actions/setup-workspace
      with:
        node-version: ${{ inputs.node-version }}

    - name: Build packages
      shell: bash
      run: |
        yarn build

    - name: Run tests
      shell: bash
      run: |
        ${{ inputs.test-command }}
