name: Run tests
description: Prepare workspace and run project tests.

inputs:
  node-version:
    description: Node.js version used for cache key.
    required: true
  test-command:
    description: Shell command used to run tests.
    required: false
    default: yarn test:coverage

runs:
  using: composite
  steps:
    - name: Setup workspace
      uses: ./.github/actions/setup-workspace
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache build outputs
      id: dist-cache
      uses: actions/cache@v4
      with:
        path: |
          packages/conventional-git/dist
          packages/conventional-bump/dist
          packages/conventional-changelog/dist
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-dist-${{ hashFiles('yarn.lock', 'package.json', 'packages/**/package.json', 'packages/**/src/**', 'packages/**/types/**', 'packages/**/tsconfig.json', 'packages/**/vite.config.ts', 'packages/**/vite.config.common.ts', 'vitest.config.ts') }}

    - name: Build packages
      if: steps.dist-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        yarn build

    - name: Run tests
      shell: bash
      run: |
        ${{ inputs.test-command }}
